---

- hosts: all
  vars:
    commit: "latest" 
  tasks:

  - name: install epel
    package:
      name: epel-release
      state: present

  - name: Install package
    package:
      name: [nginx, git]
      state: present

  - name: start and enable nginx
    service:
      name: nginx
      state: started
      enabled: true

  - name: remove html directory
    file:
      path: /usr/share/nginx/html/index.html
      state: absent

  - name: Download hugo
    get_url:
      url: https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.tar.gz
      dest: /root/

  - name: Extract hugo   
    unarchive:
      src: /root/hugo_0.70.0_Linux-64bit.tar.gz
      dest: /usr/bin/
      remote_src: yes

  - name: Get last web content
    git:
      repo: https://github.com/pierreblanc/web_content_source.git
      dest: /root/web_content_source
      force: yes

  - name: Build File
    command: hugo -D
    args:
      chdir: /root/web_content_source

  - name: Get Release repo
    git:
      repo: https://github.com/pierreblanc/web_content_source.git
      dest: /root/web_content_source
      force: yes


  - name: create release
    archive:
      path: /root/web_content_source/public
      dest: "/usr/share/nginx/html/{{commit}}.tar.gz"

  - name: get md5sum
    stat:
      path: "/usr/share/nginx/html/{{commit}}.tar.gz"
    register: stat_file

  - name: create md5 file
    copy:
      path: "/usr/share/nginx/html/{{commit}}.md5"
      content: "{{stat_file['stat']['checksum']}}"


