---

- hosts: all
  vars:
    commit: "{{tower_webhook_payload['head_commit']['id']|default('latest')}}" 
  tasks:
  - name: Ensure epel repo present
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present

#  - name: install epel
#    package:
#      name: epel-release
#      state: present

  - name: Install package
    package:
      name: [nginx, git]
      state: present

  - name: Insert releases conf
    lineinfile:
      path: /etc/nginx/nginx.conf
      insertafter: '/usr/share/nginx/html' 
      line: location /releases/ { autoindex on; }

  - name: Create releases directory
    file:
      path: /usr/share/nginx/html/releases
      state: directory

  - name: start and enable nginx
    service:
      name: nginx
      state: started
      enabled: true

  - name: remove html directory
    file:
      path: /usr/share/nginx/html/index.html
      state: absent

  - name: Download hugo
    get_url:
      url: https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.tar.gz
      dest: /root/

  - name: Extract hugo   
    unarchive:
      src: /root/hugo_0.70.0_Linux-64bit.tar.gz
      dest: /usr/bin/
      remote_src: yes

  - name: Get last web content
    git:
      repo: https://github.com/pierreblanc/web_content_source.git
      dest: /root/web_content_source
      force: yes

  - name: Build File
    command: hugo -D
    args:
      chdir: /root/web_content_source

  - name: Get Release repo
    git:
      repo: https://github.com/pierreblanc/web_content_source.git
      dest: /root/web_content_source
      force: yes


  - name: create release
    archive:
      path: /root/web_content_source/public/*
      dest: "/usr/share/nginx/html/releases/{{commit}}.tar.gz"

  - name: get md5sum
    stat:
      path: "/usr/share/nginx/html/releases/{{commit}}.tar.gz"
    register: stat_file

  - name: create md5 file
    copy:
      dest: "/usr/share/nginx/html/releases/{{commit}}.md5"
      content: "{{stat_file['stat']['checksum']}}"


