---

- hosts: all
  tasks:

  - name: install epel
    package:
      name: epel-release
      state: present

  - name: Download hugo
    get_url:
      url: https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.tar.gz
      dest: /root/

  - name: Extract hugo   
    unarchive:
      src: /root/hugo_0.70.0_Linux-64bit.tar.gz
      dest: /usr/bin/
      remote_src: yes

  - name: Get last web content
    git:
      repo: https://github.com/pierreblanc/web_content_source.git
      dest: /root/
      force: yes

  - name: Build File
    command: hugo -D
    args:
      chdir: /root/web_content
