---

- hosts: all
  vars:
    commit: "latest" 
  tasks:

  - name: install epel
    package:
      name: epel-release
      state: present

  - name: install nginx
    package:
      name: [nginx, git]
      state: present

  - name: start and enable nginx
    service:
      name: nginx
      state: started
      enabled: true

  - name: remove old html directory
    file:
      path: /usr/share/nginx/html
      state: absent

  - name: Get release tar
    get_url:
      url: "http://build/releases/{{commit}}.tar.gz"
      dest: /root/
  
  - name: create html directory
    file:
      path: /usr/share/nginx/html
      state: directory
      
  - name: untar release
    unarchive:
      src: /root/{{commit}}.tar.gz
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: remove release tar
    file:
      path: /root/{{commit}}.tar.gz
      state: absent



