---
- hosts: all
  tasks:
  
  - name: Configure HA load balancer
    block: 
      - name: Ensure epel repo present
        yum:
          name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          state: present

      - name: install haproxy
        package:
          name: haproxy
          state: present

      - name: copy haproxy conf
        template:
         src: templates/haproxy.cfg.j2
         dest: /etc/haproxy.cfg

      - name: start and enable haproxy
        service:
          name: haproxy
          state: started
          enabled: true
    when: "'tag_dev_lb' in group_names"



