---

- hosts: lb
  tasks:

  - name: install epel
    package:
      name: epel-release
      state: present

  - name: install haproxy
    package:
      name: haproxy
      state: present

  - name: start and enable haproxy
    service:
      name: haproxy
      state: started
      enabled: true

