---

- hosts: all
  tasks:

  - name: install epel
    package:
      name: epel-release
      state: present

  - name: install nginx
    package:
      name: [nginx, git]
      state: present

  - name: start and enable nginx
    service:
      name: nginx
      state: started
      enabled: true

  - name: remove html directory
    file:
      path: /usr/share/nginx/html
      state: directory
      state: absent

  - name: Get last web content
    git:
      repo: https://github.com/pierreblanc/web_content.git
      dest: /usr/share/nginx/html
      force: yes
