---

- hosts: all
  vars:
    env: "dev"
  tasks:


  - name: validate prod env
    meta: end_play
    when: env == 'prod' and not(tower_webhook_payload['ref'] is match('refs/tags/.*'))

  - name: install epel
    package:
      name: epel-release
      state: present

  - name: install nginx
    package:
      name: [nginx, git]
      state: present

  - name: start and enable nginx
    service:
      name: nginx
      state: started
      enabled: true

  - name: remove html directory
    file:
      path: /usr/share/nginx/html
      state: absent

  - name: Get last web content
    git:
      repo: https://github.com/pierreblanc/web_content.git
      dest: /usr/share/nginx/html
      force: yes
