---

- hosts: all
  tasks:

  - name: install epel
    package:
      name: epel-release
      state: present

  - name: install nginx
    package:
      name: nginx
      state: present

  - name: start and enable nginx
    service:
      name: nginx
      state: started
      enabled: true

