---
- name: Delete VMs
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - ec2_instance_facts:
      region: "{{ region | default('us-east-1') }}"
      filters:
        "tag:project": "{{ ec2_tag_name }}"
    register: ec2_list

  - debug: 
      msg: "{{ ec2_list }}"


  - name: Delete EC2 vms with project name "{{ ec2_tag_name }}"
    ec2:
      region: us-east-1
      state: 'stopped'
      wait: True
    with_items: "{{ ec2_list }}"
