---
- name: Delete VMs
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - ec2_instance_info:
      region: "{{ region | default('us-east-1') }}"
      filters:
        "tag:project": "{{ project_name }}"
    register: ec2_list

  - debug: 
      msg: "{{ item.instance_id }}"
    loop: "{{ ec2_list.instances }}"


  - name: Delete EC2 vms with project name "{{ project_name }}"
    ec2: 
      instance_ids: "{{ item.instance_id }}"
      region: us-east-1
      state: "{{ status_ec2 | default('stopped') }}"
#      wait: True
    with_items: "{{ ec2_list.instances }}"
