---
- name: Delete VMs
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - ec2_instance_info:
      region: "{{ region | default('us-east-1') }}"
      filters:
        "tag:project": "{{ ec2_tag_name }}"
    register: ec2_list

  - debug: 
      msg: "{{ item.instance_id }}"
    with_items: "{{ ec2_list.instances }}"


  - name: Delete EC2 vms with project name "{{ ec2_tag_name }}"
    ec2: 
      instance_ids: "{{ item.instance_id }}"
      region: us-east-1
      state: 'stopped'
      wait: True
    with_items: "{{ ec2_list.instances }}"
