---
- name: Delete VMs
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: Delete EC2 vms with project name "{{ project_name_tag }}"
    ec2:
      instance_tags:
        project_name: "{{ project_name_tag }}"
      region: us-east-1
      state: absent
      wait: True
