# define in survey servicenow_username and servicenow_password
# You can use EE quay.io/acme_corp/servicenow-ee:latest	

---
- name: Open a ServiceNow ticket
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - servicenow.itsm
  
  vars:
    servicenow_instance: "https://ansible.service-now.com"
    #servicenow_username: "your-username"
    #servicenow_password: "your-password"
    ticket_short_description: "Ansible Deploy new build"
    ticket_description: "A new build was pushed into the dev env."

  tasks:

    - name: Create a ServiceNow ticket
      servicenow.itsm.incident:
        instance:
          host: "{{ servicenow_instance }}"
          username: "{{ servicenow_username }}"
          password: "{{ servicenow_password }}"
        state: new
        caller: "{{ servicenow_username }}"
        short_description: "[{{ ansible_user }}] created a new incident from Ansible Automation Platform"
        description: "A new deployment started"
        impact: low
        urgency: low
      register: new_incident


    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"
        


